/* OFMJ — registry de templates (editor unificado) */
const OFMJ_BASE = 'marcas/ofmj/';
const ofmjAsset = (p) => (p && (p.startsWith('http') || p.startsWith('data:')) ? p : `${OFMJ_BASE}${p}`);

// editor-templates.jsx — Registry para o editor form-based.
// Cada entrada descreve: identidade, dimensões, defaults (estado inicial do
// form), fields[] (UI dos campos editáveis) e render(content, tweak).
//
// Os componentes em templates.jsx aceitam content opcional com fallback para
// os mesmos defaults — duplicação consciente: os defaults aqui semeiam o form,
// os defaults lá garantem que o canvas-Figma continua a renderizar sem editor.

// Resolve via window: cada <script type="text/babel"> pode ser embrulhado
// numa IIFE pelo Babel standalone, portanto referências cruzadas a function
// declarations doutro bloco não são garantidas — window é o ponto de acordo.
const {
  S01_Capa, S02_Definicao, S03_Citacao, S04_TeologiaEmCores, S05_Lista, S06_Fecho,
  T_Liturgia, T_Leitura, T_Caderno, T_Story,
} = window;

const TPL_GROUPS = {
  SERIE: 'Série · Ícones cristãos',
  STANDALONE: 'Standalone',
  STORY: 'Story 9:16',
};

const OFMJ_TEMPLATES = [
  // ── Série âncora — 6 slides ─────────────────────────────────
  {
    id: 's01-capa',
    name: '01 · Capa',
    group: TPL_GROUPS.SERIE,
    w: 1080, h: 1350,
    defaults: {
      section: '01',
      category: 'TRADIÇÃO VIVA',
      eyebrow: 'Pilar II — Tradição viva',
      title: 'O que são <em>ícones</em> cristãos?',
      subtitle: '— uma introdução anglicana',
      image: ofmjAsset('assets/perpetuo-socorro.webp'),
      imageAlt: 'Nossa Senhora do Perpétuo Socorro',
      folio: 1,
      total: 6,
    },
    fields: [
      { name: 'section',  label: 'Marca · número',   type: 'text', hint: 'Ex.: 01, 02, LIT, ST' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'eyebrow',  label: 'Sobre-título',     type: 'text' },
      { name: 'title',    label: 'Título',           type: 'rich', hint: 'Aceita <em>itálico</em>, <br/> para quebra' },
      { name: 'subtitle', label: 'Subtítulo',        type: 'text' },
      { name: 'image',    label: 'Imagem principal', type: 'image' },
      { name: 'imageAlt', label: 'Texto alternativo da imagem', type: 'text' },
      { name: 'folio',    label: 'Página',           type: 'number' },
      { name: 'total',    label: 'Total de páginas', type: 'number' },
    ],
    render: (content, tweak) => <S01_Capa tweak={tweak} content={content} />,
  },
  {
    id: 's02-definicao',
    name: '02 · Definição',
    group: TPL_GROUPS.SERIE,
    w: 1080, h: 1350,
    defaults: {
      section: '02',
      category: 'DEFINIÇÃO',
      titleA: 'O que <em>são</em>.',
      bodyA: 'Ícones são imagens cristãs usadas pela tradição antiga da Igreja como auxílio para <strong>oração</strong>, <strong>contemplação</strong> e <strong>ensino</strong> da fé.',
      titleB: 'O que <em>não</em> são.',
      bodyB: 'Não são deuses. Não são objectos de adoração. São representações visuais que apontam para Cristo e para as verdades do evangelho.',
      folio: 2,
      total: 6,
    },
    fields: [
      { name: 'section',  label: 'Marca · número',    type: 'text' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'titleA', label: 'Título A',  type: 'rich', hint: '<em> e <strong> aceites' },
      { name: 'bodyA',  label: 'Corpo A',   type: 'textarea-rich' },
      { name: 'titleB', label: 'Título B',  type: 'rich' },
      { name: 'bodyB',  label: 'Corpo B',   type: 'textarea-rich' },
      { name: 'folio',  label: 'Página',           type: 'number' },
      { name: 'total',  label: 'Total de páginas', type: 'number' },
    ],
    render: (content, tweak) => <S02_Definicao tweak={tweak} content={content} />,
  },
  {
    id: 's03-citacao',
    name: '03 · Citação',
    group: TPL_GROUPS.SERIE,
    w: 1080, h: 1350,
    defaults: {
      section: '03',
      category: 'JANELAS PARA O REINO',
      bgImage: ofmjAsset('assets/foto-altar-domestico.png'),
      quoteEyebrow: 'Tradição oriental',
      quote: '“Janelas<br/>para o <span style="color:var(--accent)">Reino</span>.”',
      body: 'Não porque o ícone seja Deus — mas porque celebra a encarnação: em Jesus, Deus se fez visível. <em>Pintar Cristo</em> é confessar que o Verbo se fez carne.',
      folio: 3,
      total: 6,
    },
    fields: [
      { name: 'section',  label: 'Marca · número',    type: 'text' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'bgImage',  label: 'Imagem de fundo (esmaecida)', type: 'image' },
      { name: 'quoteEyebrow', label: 'Sobre-título da citação', type: 'text' },
      { name: 'quote', label: 'Citação',  type: 'rich', hint: '<br/> para quebrar; <span style="color:var(--accent)">palavra</span> para destacar' },
      { name: 'body',  label: 'Glosa',    type: 'textarea-rich' },
      { name: 'folio', label: 'Página',           type: 'number' },
      { name: 'total', label: 'Total de páginas', type: 'number' },
    ],
    render: (content, tweak) => <S03_Citacao tweak={tweak} content={content} />,
  },
  {
    id: 's04-tese',
    name: '04 · Tese',
    group: TPL_GROUPS.SERIE,
    w: 1080, h: 1350,
    defaults: {
      section: '04',
      category: 'TESE',
      intro: 'A Igreja chamou-lhes',
      title: '<em style="color:var(--accent)">teologia</em><br/>em cores.',
      body: 'Não decoração — <strong>argumento</strong>.',
      bodySoft: 'Imagem que ensina o que palavra sozinha não alcança.',
      historic: 'No 2.º Concílio de Niceia (787), a Igreja defendeu isto contra o império iconoclasta.',
      folio: 4,
      total: 6,
    },
    fields: [
      { name: 'section',  label: 'Marca · número',    type: 'text' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'intro',    label: 'Introdução',  type: 'text' },
      { name: 'title',    label: 'Título grande', type: 'rich' },
      { name: 'body',     label: 'Corpo forte',  type: 'rich' },
      { name: 'bodySoft', label: 'Corpo suave',  type: 'textarea' },
      { name: 'historic', label: 'Nota histórica', type: 'textarea' },
      { name: 'folio',    label: 'Página',           type: 'number' },
      { name: 'total',    label: 'Total de páginas', type: 'number' },
    ],
    render: (content, tweak) => <S04_TeologiaEmCores tweak={tweak} content={content} />,
  },
  {
    id: 's05-lista',
    name: '05 · Lista (3 cards)',
    group: TPL_GROUPS.SERIE,
    w: 1080, h: 1350,
    defaults: {
      section: '05',
      category: 'POR ONDE COMEÇAR',
      title: 'Três ícones para<br/>começar a <em>olhar</em>.',
      card1Num: 'i.',
      card1Img: ofmjAsset('assets/foto-pantocrator.png'),
      card1Pos: 'center 28%',
      card1Name: 'Cristo Pantocrátor',
      card1Meta: 'séc. VI · Sinai',
      card1Line: 'O Senhor que olha de frente.',
      card2Num: 'ii.',
      card2Img: ofmjAsset('assets/foto-perpetuo-socorro.png'),
      card2Pos: 'center 38%',
      card2Name: 'Perpétuo Socorro',
      card2Meta: 'tradição bizantina',
      card2Line: 'A mãe que aponta para o Filho.',
      card3Num: 'iii.',
      card3Img: ofmjAsset('assets/foto-ultima-ceia.png'),
      card3Pos: 'center 38%',
      card3Name: 'Última Ceia',
      card3Meta: 'ceia mística',
      card3Line: 'A comunhão que é centro da vida.',
      folio: 5,
      total: 6,
    },
    fields: [
      { name: 'section',  label: 'Marca · número',    type: 'text' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'title', label: 'Título', type: 'rich' },
      { name: 'card1Num',  label: 'Card 1 · numeração', type: 'text' },
      { name: 'card1Img',  label: 'Card 1 · imagem',    type: 'image' },
      { name: 'card1Pos',  label: 'Card 1 · object-position', type: 'text', hint: "Ex.: 'center 28%'" },
      { name: 'card1Name', label: 'Card 1 · nome',      type: 'text' },
      { name: 'card1Meta', label: 'Card 1 · metadata',  type: 'text' },
      { name: 'card1Line', label: 'Card 1 · frase',     type: 'text' },
      { name: 'card2Num',  label: 'Card 2 · numeração', type: 'text' },
      { name: 'card2Img',  label: 'Card 2 · imagem',    type: 'image' },
      { name: 'card2Pos',  label: 'Card 2 · object-position', type: 'text' },
      { name: 'card2Name', label: 'Card 2 · nome',      type: 'text' },
      { name: 'card2Meta', label: 'Card 2 · metadata',  type: 'text' },
      { name: 'card2Line', label: 'Card 2 · frase',     type: 'text' },
      { name: 'card3Num',  label: 'Card 3 · numeração', type: 'text' },
      { name: 'card3Img',  label: 'Card 3 · imagem',    type: 'image' },
      { name: 'card3Pos',  label: 'Card 3 · object-position', type: 'text' },
      { name: 'card3Name', label: 'Card 3 · nome',      type: 'text' },
      { name: 'card3Meta', label: 'Card 3 · metadata',  type: 'text' },
      { name: 'card3Line', label: 'Card 3 · frase',     type: 'text' },
      { name: 'folio', label: 'Página',           type: 'number' },
      { name: 'total', label: 'Total de páginas', type: 'number' },
    ],
    render: (content, tweak) => <S05_Lista tweak={tweak} content={content} />,
  },
  {
    id: 's06-fecho',
    name: '06 · Fecho · CTA',
    group: TPL_GROUPS.SERIE,
    w: 1080, h: 1350,
    defaults: {
      section: '06',
      category: 'FECHO',
      title: '<span style="color:var(--accent)">Anglicanos</span> têm ícones?',
      answerShort: 'A resposta curta é <strong>sim</strong>.',
      answerLong: 'A longa é mais interessante.',
      teaser: '— próximo post da série.',
      cta1: '<strong>Salva</strong> para reler com calma.',
      cta2: '<strong>ofantasticomundodejorge</strong>',
      folio: 6,
      total: 6,
    },
    fields: [
      { name: 'section',  label: 'Marca · número',    type: 'text' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'title',       label: 'Pergunta',       type: 'rich' },
      { name: 'answerShort', label: 'Resposta curta', type: 'rich' },
      { name: 'answerLong',  label: 'Frase de gancho', type: 'text' },
      { name: 'teaser',      label: 'Teaser próximo post', type: 'text' },
      { name: 'cta1',        label: 'CTA 1 (📌)',      type: 'rich' },
      { name: 'cta2',        label: 'CTA 2 (@)',       type: 'rich' },
      { name: 'folio', label: 'Página',           type: 'number' },
      { name: 'total', label: 'Total de páginas', type: 'number' },
    ],
    render: (content, tweak) => <S06_Fecho tweak={tweak} content={content} />,
  },

  // ── Standalone ────────────────────────────────────────────────
  {
    id: 't-liturgia',
    name: 'Liturgia · calendário',
    group: TPL_GROUPS.STANDALONE,
    w: 1080, h: 1350,
    defaults: {
      section: 'LIT',
      category: 'ANO LITÚRGICO',
      date: '03 · DEZ · 2026',
      weekday: 'Domingo',
      weekNum: 'I',
      title: 'Adventus',
      subtitle: 'Vinda — o tempo da espera.',
      quote: '“Vigiai, pois, porque não sabeis em<br/>que dia vem o vosso Senhor.”',
      reference: 'Mt 24.42 · Colecta do Domingo I',
      colorLabel: 'Cor litúrgica',
      colorHex: '#4a3a6e',
      colorName: 'Violeta',
      psalmLabel: 'Salmo',
      psalm: '122',
    },
    fields: [
      { name: 'section',  label: 'Marca · número',    type: 'text' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'date',     label: 'Marca · data',      type: 'text' },
      { name: 'weekday',  label: 'Dia da semana',     type: 'text' },
      { name: 'weekNum',  label: 'Numeração grande (Romano/arábico)', type: 'text' },
      { name: 'title',    label: 'Nome do tempo',     type: 'text' },
      { name: 'subtitle', label: 'Glosa',             type: 'text' },
      { name: 'quote',    label: 'Citação',           type: 'rich' },
      { name: 'reference', label: 'Referência',       type: 'text' },
      { name: 'colorLabel', label: 'Label · cor',     type: 'text' },
      { name: 'colorHex',  label: 'Cor litúrgica (hex)', type: 'text', hint: 'Ex.: #4a3a6e (violeta), #722f37 (vermelho), #ffffff (branco)' },
      { name: 'colorName', label: 'Nome da cor',      type: 'text' },
      { name: 'psalmLabel', label: 'Label · salmo',   type: 'text' },
      { name: 'psalm',     label: 'Número do salmo',  type: 'text' },
    ],
    render: (content, tweak) => <T_Liturgia tweak={tweak} content={content} />,
  },
  {
    id: 't-leitura',
    name: 'Nota de leitura',
    group: TPL_GROUPS.STANDALONE,
    w: 1080, h: 1350,
    defaults: {
      section: 'LEI',
      category: 'NOTA DE LEITURA',
      date: 'MAIO · 2026',
      cover: ofmjAsset('assets/livro-nouwen.jpeg'),
      coverAlt: 'Contempla a Face do Senhor — Henri Nouwen',
      eyebrow: 'Espiritualidade · Ícones',
      title: 'Contempla a<br/><em>Face do Senhor</em>',
      author: 'Henri J. M. Nouwen',
      tagline: '— orar com ícones.',
      metaEdit: 'Edições Loyola',
      metaPags: '96',
      metaLido: '2 noites · lento',
      sectionWhy: 'Por que ler isto hoje',
      body: 'Nouwen escreve como pastor que aprendeu, já maduro, a <em>olhar</em>. Quatro ícones russos, quatro modos de presença. Um pequeno manual de atenção — a própria condição da oração.',
    },
    fields: [
      { name: 'section',  label: 'Marca · número',    type: 'text' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'date',     label: 'Marca · data',      type: 'text' },
      { name: 'cover',    label: 'Capa do livro',     type: 'image' },
      { name: 'coverAlt', label: 'Texto alternativo da capa', type: 'text' },
      { name: 'eyebrow',  label: 'Categoria editorial', type: 'text' },
      { name: 'title',    label: 'Título do livro',   type: 'rich' },
      { name: 'author',   label: 'Autor',             type: 'text' },
      { name: 'tagline',  label: 'Tagline',           type: 'text' },
      { name: 'metaEdit', label: 'Editora',           type: 'text' },
      { name: 'metaPags', label: 'Páginas',           type: 'text' },
      { name: 'metaLido', label: 'Tempo/forma de leitura', type: 'text' },
      { name: 'sectionWhy', label: 'Label · porquê',  type: 'text' },
      { name: 'body',     label: 'Por que ler',       type: 'textarea-rich' },
    ],
    render: (content, tweak) => <T_Leitura tweak={tweak} content={content} />,
  },
  {
    id: 't-caderno',
    name: 'Caderno · bastidores',
    group: TPL_GROUPS.STANDALONE,
    w: 1080, h: 1350,
    defaults: {
      bgImage: ofmjAsset('assets/estudo-icones.jpeg'),
      markerA: 'CADERNO',
      markerB: 'BASTIDORES',
      date: 'MAIO · 2026',
      title: 'Onde a tradição<br/><em>se lê</em>.',
      body: 'Pantocrátor à esquerda. Agostinho a escrever logo abaixo. E entre eles, a estante: Bultmann, Spring, teologia do NT, um par de manuais de firewalls. <em>É daqui que se fala.</em>',
      handle: '@ofantasticomundodejorge',
    },
    fields: [
      { name: 'bgImage', label: 'Foto de fundo (full bleed)', type: 'image' },
      { name: 'markerA', label: 'Marca · esquerda', type: 'text' },
      { name: 'markerB', label: 'Marca · meio',     type: 'text' },
      { name: 'date',    label: 'Marca · data',     type: 'text' },
      { name: 'title',   label: 'Título',           type: 'rich' },
      { name: 'body',    label: 'Corpo',            type: 'textarea-rich' },
      { name: 'handle',  label: 'Handle / rodapé',  type: 'text' },
    ],
    render: (content, tweak) => <T_Caderno tweak={tweak} content={content} />,
  },

  // ── Story 9:16 ────────────────────────────────────────────────
  {
    id: 't-story',
    name: 'Story · citação',
    group: TPL_GROUPS.STORY,
    w: 1080, h: 1920,
    defaults: {
      section: 'ST',
      category: 'NOTA RÁPIDA',
      quote: 'A tradição<br/>não é um <em style="color:var(--accent)">museu</em>.<br/>É uma <em>conversa</em><br/>que continua.',
      attribution: '— J.G., caderno MATS · §17',
    },
    fields: [
      { name: 'section',  label: 'Marca · número',    type: 'text' },
      { name: 'category', label: 'Marca · categoria', type: 'text' },
      { name: 'quote',       label: 'Citação',        type: 'rich', hint: '<br/> para quebra; <em>itálico</em>' },
      { name: 'attribution', label: 'Atribuição',     type: 'text' },
    ],
    render: (content, tweak) => <T_Story tweak={tweak} content={content} />,
  },
];

// Galeria de imagens reutilizáveis. À medida que se acumulam fotos curadas
// em assets/galeria/, listar aqui — campo image expõe esta lista + upload.
const OFMJ_GALERIA = [
  ofmjAsset('uploads/WhatsApp Image 2026-04-21 at 19.01.27.jpeg'),
  ofmjAsset('uploads/nossa-senhora-perpetuo-socorro-quadro-icone-755738.webp'),
  ofmjAsset('uploads/WhatsApp Image 2026-05-18 at 20.18.06.jpeg'),
  ofmjAsset('uploads/WhatsApp Image 2026-04-16 at 11.22.41.jpeg'),
  ofmjAsset('uploads/WhatsApp Image 2026-05-18 at 20.54.31.jpeg'),
  ofmjAsset('uploads/WhatsApp Image 2026-05-18 at 20.54.31 (1).jpeg'),
  ofmjAsset('uploads/WhatsApp Image 2026-04-28 at 08.36.05.jpeg'),
  ofmjAsset('uploads/WhatsApp Image 2026-04-28 at 08.36.06.jpeg'),
  ofmjAsset('uploads/WhatsApp Image 2026-04-10 at 18.21.18.jpeg'),
  ofmjAsset('uploads/WhatsApp Image 2026-04-21 at 19.01.27 (1).jpeg'),
  ofmjAsset('assets/perpetuo-socorro.webp'),
  ofmjAsset('assets/foto-pantocrator.png'),
  ofmjAsset('assets/foto-perpetuo-socorro.png'),
  ofmjAsset('assets/foto-ultima-ceia.png'),
  ofmjAsset('assets/foto-altar-domestico.png'),
  ofmjAsset('assets/livro-nouwen.jpeg'),
  ofmjAsset('assets/estudo-icones.jpeg'),
];

Object.assign(window, { OFMJ_TEMPLATES, OFMJ_GALERIA, TPL_GROUPS });
